INSERT INTO PRODUCTGROUP (PRODUCTGROUPNAME) VALUES ('Tiết kiệm');
INSERT INTO PRODUCTGROUP (PRODUCTGROUPNAME) VALUES ('Tài khoản');
INSERT INTO PRODUCTGROUP (PRODUCTGROUPNAME) VALUES ('Cho vay');
INSERT INTO PRODUCTGROUP (PRODUCTGROUPNAME) VALUES ('Thẻ');
INSERT INTO PRODUCTGROUP (PRODUCTGROUPNAME) VALUES ('Ngân hàng điện tử');
INSERT INTO PRODUCTGROUP (PRODUCTGROUPNAME) VALUES ('Bảo hiểm');
INSERT INTO PRODUCTGROUP (PRODUCTGROUPNAME) VALUES ('Sản phẩm dịch vụ khác');

INSERT INTO PRODUCT (PRODUCTNAME, PRODUCTDESCRIPTION, PRODUCTGROUPID) VALUES ('Tiết kiệm vô đối!', 'Ta là siêu nhân', 1)

INSERT INTO GROUPS (GROUPID, GROUPNAME, GROUPDESCRIPTION) VALUES (1, 'Hacker', 'Hacker first!');
INSERT INTO GROUPS (GROUPID, GROUPNAME, GROUPDESCRIPTION) VALUES (2, 'RegularUser', 'Chicken!');
INSERT INTO GROUPS (GROUPID, GROUPNAME, GROUPDESCRIPTION) VALUES (3, 'BankingOfficer', 'Cat!');
INSERT INTO GROUPS (GROUPID, GROUPNAME, GROUPDESCRIPTION) VALUES (4, 'Admin', 'Nine Tail Fox!');
INSERT INTO GROUPS (GROUPID, GROUPNAME, GROUPDESCRIPTION) VALUES (5, 'Hacker Again', 'Hacker last!');

INSERT INTO BRANCH (BRANCHNAME, BRANCHLOCATION, BRANCHPHONE)
			VALUES ('Trụ sở', '155 Trường Chinh, Hà Nội', '(043) 565 8451');
INSERT INTO BRANCH (BRANCHNAME, BRANCHLOCATION, BRANCHPHONE)
			VALUES ('Chi nhánh tại Vinh', 'Trên biển Cửa Lò :)', '(0351) xxx xxxx');
INSERT INTO BRANCH (BRANCHNAME, BRANCHLOCATION, BRANCHPHONE)
			VALUES ('Chi nhánh tại Huế', 'Địa chỉ bác Thuỳ :)', '(xxx) xxx xxxx');
INSERT INTO BRANCH (BRANCHNAME, BRANCHLOCATION, BRANCHPHONE)
			VALUES ('Chi nhánh tại TP. Hồ Chí Minh', '275 Điện Biên Phủ, P.7, Q.3', '(08) xxx xxxx');